### ISSUE TITLE
running using fasta file

### ISSUE THREAD

**Issue by najibveto** [broadinstitute/adapt#72]
hello,
i am trying to run the following command:
`design.py [complete-targets] fasta [INHV_N.fasta] -o [out-tsv]`
however i got the following error:
```
usage: design.py [-h] {sliding-window,complete-targets} ...
design.py: error: argument search_cmd: invalid choice: '[-h]' (choose from 'sliding-window', 'complete-targets')
```
i would like to know what is the correct command for doing it.
thank you for your help.

**Comment by haydenm** [comment]
The command that you run should not contain the square brackets, `[` and `]`; these indicate what you should fill in. For instance, in your example, the command you run could be:
```
design.py complete-targets fasta INHV_N.fasta -o out
```
Sorry for the confusion about this in the README.

The [examples section in the README](https://github.com/broadinstitute/adapt#examples) has additional examples without the square brackets.

**Comment by najibveto** [comment]
> The command that you run should not contain the square brackets, `[` and `]`; these indicate what you should fill in. For instance, in your example, the command you run could be:
> 
> ```
> design.py complete-targets fasta INHV_N.fasta -o out
> ```
> 
> Sorry for the confusion about this in the README.
> 
> The [examples section in the README](https://github.com/broadinstitute/adapt#examples) has additional examples without the square brackets.

thank a lot for yoru reply.
just one question if possible, i run the command and i got the following message:
```
Traceback (most recent call last):
  File "/home/najib/miniconda3/envs/adapt/bin/design.py", line 1728, in <module>
    run(argv_to_args(sys.argv))
  File "/home/najib/miniconda3/envs/adapt/bin/design.py", line 970, in run
    design_for_id(args)
  File "/home/najib/miniconda3/envs/adapt/bin/design.py", line 756, in design_for_id
    raise Exception(("Either --predict-activity-model-path or "
Exception: Either --predict-activity-model-path or --predict-cas13a-activity-model must be specified if --obj is 'maximize-activity'. Alternatively, if you cannot use our pre-trained Cas13a model nor another model, you can set --use-simple-binary-activity-prediction
```
i run it again and i got the results.
i am curious should i opt for pre-trained Cas13a and can give better accuracy?.
thank you for your help.

**Comment by haydenm** [comment]
I suggest using the model, by specifying `--predict-cas13a-activity-model`, if and only if the designs are to be used for RNA detection with LwaCas13a. Otherwise, you could specify `--use-simple-binary-activity-prediction` to instead use a simple mismatch and PFS-based model for the crRNAs.

**Comment by najibveto** [comment]
> I suggest using the model, by specifying `--predict-cas13a-activity-model`, if and only if the designs are to be used for RNA detection with LwaCas13a. Otherwise, you could specify `--use-simple-binary-activity-prediction` to instead use a simple mismatch and PFS-based model for the crRNAs.

thank you a lot for your help.
